language: php

php:
    - 5.6
    - 7.0
    - hhvm
    
matrix:
  allow_failures:
    - php: hhvm

services:
    - mysql

script: phpunit --configuration tests/phpunit.xml

before_script:
    - travis_retry composer self-update
    - mysql -e 'create database routers;'
    - cp ./tests/config.travis.yml ./config.yml

before_install:
    - pip install --user codecov

after_success:
    - codecov
  