language: php

php:
    - 5.6
    - 7.0
    - hhvm
    
matrix:
  allow_failures:
    - php: hhvm

services:
    - mysql

script: 
    - phpunit --configuration tests/phpunit.xml --coverage-text --coverage-clover=coverage.xml

before_script:
    - travis_retry composer self-update
    - travis_retry composer require codeclimate/php-test-reporter --no-dev
    - travis_retry composer install
    - mysql -e 'create database routers;'
    - cp ./tests/config.travis.yml ./config.yml

after_script:
    - CODECLIMATE_REPO_TOKEN="7bf23171d2ee8d1c8d5685751247e50c473098c627783acf6ce6b462ff434ebd" ./vendor/bin/test-reporter --stdout > codeclimate.json

before_install:
    - pip install --user codecov

after_success:
    - codecov

addons:
    code_climate:
        repo_token: 7bf23171d2ee8d1c8d5685751247e50c473098c627783acf6ce6b462ff434ebd
