language: php

php:
    - 5.6
    - 7.0
    - hhvm
    
matrix:
  allow_failures:
    - php: hhvm

script: phpunit --configuration tests/phpunit.xml

before_script:
    - travis_retry composer self-update
